const categoriasFemininas = ['vestidos', 'blusas', 'saias', 'calcas', 'shorts', 'conjuntos'];

const produtos = [
  { id: 1, nome: 'Vestido midi', tipo: 'vestidos', preco: 289.90, tamanhos: 'PP ao GG', imagem: 'https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=600&q=85', badge: 'novo' },
  { id: 2, nome: 'Vestido midi', tipo: 'vestidos', preco: 319.90, tamanhos: 'P ao G3', imagem: 'https://images.unsplash.com/photo-1566174053879-31528523f8ae?auto=format&fit=crop&w=600&q=85', badge: 'favorito' },
  { id: 3, nome: 'Vestido curto', tipo: 'vestidos', preco: 259.90, tamanhos: 'PP ao G2', imagem: 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?auto=format&fit=crop&w=600&q=85', badge: '' },
  { id: 4, nome: 'Vestido midi floral', tipo: 'vestidos', preco: 249.90, tamanhos: 'PP ao G3', imagem: 'https://i.pinimg.com/236x/91/ea/a8/91eaa86abc924eb077bc65ea578ee71b.jpg', badge: 'novo' },
  { id: 5, nome: 'Look com casaco e calça', tipo: 'conjuntos', preco: 399.90, tamanhos: 'P ao G2', imagem: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-kpdY5bJcba1ygyMNYlW45AJjo_YZp1Jsww_dbMuc2Q&s=10', badge: 'editorial' },
  { id: 6, nome: 'Look com blusa e saia', tipo: 'conjuntos', preco: 349.90, tamanhos: 'P ao G3', imagem: 'https://st2.depositphotos.com/5849560/12291/i/950/depositphotos_122919560-stock-photo-outdoor-full-body-portrait-of.jpg', badge: 'novo' },
  { id: 7, nome: 'Look com camisa e saia', tipo: 'conjuntos', preco: 229.90, tamanhos: '34 ao 46', imagem: 'https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?auto=format&fit=crop&w=600&q=85', badge: 'novo' },
  { id: 8, nome: 'Jaqueta de couro', tipo: 'jaqueta', preco: 199.90, tamanhos: 'PP ao G2', imagem: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=600&q=85', badge: '' },
  { id: 9, nome: 'Calça', tipo: 'calcas', preco: 219.90, tamanhos: '36 ao 46', imagem: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRFND5DyuglzYoD9x-mKz_6i0ElVRZIi0s3uqWZbzMj2w&s', badge: 'popular' },
  { id: 10, nome: 'Calça jeans', tipo: 'calcas', preco: 279.90, tamanhos: '36 ao 48', imagem: 'https://images.unsplash.com/photo-1542272604-787c3835535d?auto=format&fit=crop&w=600&q=85', badge: 'mais vendida' },
  { id: 11, nome: 'Calça slim', tipo: 'calcas', preco: 319.90, tamanhos: 'P ao G3', imagem: 'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?auto=format&fit=crop&w=600&q=85', badge: 'novo' },
  { id: 12, nome: 'Look com casaco e saia jeans', tipo: 'conjuntos', preco: 289.90, tamanhos: '38 ao 48', imagem: 'https://st4.depositphotos.com/1000824/24266/i/1600/depositphotos_242662816-stock-photo-full-body-young-beautiful-brunette.jpg', badge: 'elegance' },
  { id: 13, nome: 'Shorts jeans destroyed', tipo: 'shorts', preco: 159.90, tamanhos: 'PP ao GG', imagem: 'https://images.unsplash.com/photo-1591195853828-11db59a44f6b?auto=format&fit=crop&w=600&q=85', badge: '' },
  { id: 14, nome: 'Jaquetas femininas', tipo: 'blusas', preco: 179.90, tamanhos: '36 ao 46', imagem: 'https://images.unsplash.com/photo-1551488831-00ddcb6c6bd3?auto=format&fit=crop&w=600&q=85', badge: 'verão' },
  { id: 15, nome: 'Camiseta preta estampada', tipo: 'blusas', preco: 149.90, tamanhos: 'PP ao GG', imagem: 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=600&q=85', badge: 'novo' },
  { id: 16, nome: 'Look com camiseta e jeans', tipo: 'conjuntos', preco: 139.90, tamanhos: 'P ao G2', imagem: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=600&q=85', badge: '' },
  { id: 17, nome: 'Look de inverno com casaco', tipo: 'conjuntos', preco: 159.90, tamanhos: 'PP ao G3', imagem: 'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=600&q=85', badge: 'essencial' },
  { id: 18, nome: 'Blusa oversized', tipo: 'blusas', preco: 169.90, tamanhos: 'P ao G2', imagem: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRaR_5MgL1Cbx5oenVoufpNbBOPGbPElLxuwcxH2QzGVwE1g7oe0cbSnXZh&s=10', badge: 'novo' },
  { id: 19, nome: 'Conjunto casual', tipo: 'conjuntos', preco: 329.90, tamanhos: 'PP ao G2', imagem: 'https://images.unsplash.com/photo-1485968579580-b6d095142e6e?auto=format&fit=crop&w=600&q=85', badge: 'conjunto' },
  { id: 20, nome: 'Conjunto de verão', tipo: 'conjuntos', preco: 299.90, tamanhos: 'P ao G2', imagem: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=600&q=85', badge: 'novo' },
  { id: 21, nome: 'Conjunto minimalista', tipo: 'conjuntos', preco: 289.90, tamanhos: 'PP ao G2', imagem: 'https://i.pinimg.com/736x/db/7e/d9/db7ed96b0ea2dc6a6b6802884c035574.jpg', badge: 'popular' },
  { id: 22, nome: 'Conjunto alfaiataria', tipo: 'conjuntos', preco: 419.90, tamanhos: 'P ao G3', imagem: 'https://m.magazineluiza.com.br/a-static/420x420/conjunto-alfaiataria-feminino-3-pecas-roupas-femininas-elegante-calca-pantalona-e-camisa-social-bella-top-moda/bellatopmoda2/calcam1/b24c629c54782bd36c21d45bf5d43cec.jpeg', badge: 'premium' },
  { id: 23, nome: 'Vestido floral rosa', tipo: 'vestidos', preco: 279.90, tamanhos: 'P ao G2', imagem: 'https://down-br.img.susercontent.com/file/sg-11134201-7rbmp-lnb2nxwna5ei6e', badge: 'novo' },
  { id: 24, nome: 'Conjunto blazer e saia', tipo: 'conjuntos', preco: 359.90, tamanhos: 'P ao G3', imagem: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQcdotucoTZwGcLk27Z5nZtLTKqYyLiE6ShORIMTS5cRrs_ZBmImvyzAok&s=10', badge: 'elegante' },
  { id: 25, nome: 'Blusa de tricô', tipo: 'blusas', preco: 179.90, tamanhos: 'P ao G2', imagem: 'https://img.kwcdn.com/product/fancy/beb04578-3f93-49d8-88da-a84d76580f1d.jpg?imageMogr2/auto-orient%7CimageView2/2/w/800/q/70/format/webp', badge: 'novo' },
  { id: 26, nome: 'Saia curta', tipo: 'saias', preco: 189.90, tamanhos: '36 ao 42', imagem: 'https://mariafilo.vtexassets.com/arquivos/ids/502159-500-750/1522722_10007_1-SAIA-CURTA-PALA-BORDADO.jpg?v=638790307693230000', badge: 'novo' },
  { id: 27, nome: 'Regata', tipo: 'blusas', preco: 149.90, tamanhos: 'P ao G2', imagem: 'https://minimadeia.com/cdn/shop/files/103301MRC-regata-gola-alta-hibisco-marrom-claro-minimadeia-jun26-08.webp?crop=center&height=2520&v=1782494048&width=1800', badge: 'novo' },
  { id: 28, nome: 'Conjunto estampado', tipo: 'conjuntos', preco: 389.90, tamanhos: 'P ao G3', imagem: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSIDnbxYIvN4kQoRINaeSdRhnQCpMMPNlXGAhKYl2kGmHlJ76JP1s0pS_k&s=10', badge: 'editorial' },
  { id: 29, nome: 'Conjunto refinado', tipo: 'conjuntos', preco: 429.90, tamanhos: 'P ao G2', imagem: 'https://d3vnyi5j6ba1mc.cloudfront.net/Custom/Content/Products/28/77/2877897_conjunto-feminino-com-detalhes-2222200022_m1_639231560138045620.webp', badge: 'premium' },
  { id: 30, nome: 'Blusa com drapeado', tipo: 'blusas', preco: 169.90, tamanhos: 'PP ao G2', imagem: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS0hqtE7qBoIwkTrUMfg-IgY0dWU4_MQaFilHwHAE-hyg&s', badge: 'novo' },
  { id: 31, nome: 'Calça jeans', tipo: 'calcas', preco: 299.90, tamanhos: '36 ao 46', imagem: 'https://dot.cdn.magazord.com.br/img/2026/09/produto/21726/06-calca-jeans-pantalona-lateral-bicolor.jpeg?ims=475x650', badge: 'novo' },
  { id: 32, nome: 'Vestido midi transpassado', tipo: 'vestidos', preco: 379.90, tamanhos: 'P ao G2', imagem: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSPzuNE934vSXlUOEfadZc1q0zDZn2xPNp6mlyD47DllDjrmpQVaGK3f5g&s=10', badge: 'favorito' },
  { id: 33, nome: 'Vestido midi tomara que caia', tipo: 'vestidos', preco: 349.90, tamanhos: 'P ao G3', imagem: 'https://http2.mlstatic.com/D_NQ_NP_798295-MLB103561214662_012026-O-2026-outono-e-inverno-novas-roupas-femininas.webp', badge: 'novo' },
  { id: 34, nome: 'Vestido midi', tipo: 'vestidos', preco: 329.90, tamanhos: 'PP ao G2', imagem: 'https://i.pinimg.com/736x/e7/9b/1e/e79b1ec427b623ea7f82ed3e7c6704a5.jpg', badge: 'casual' },
  { id: 35, nome: 'Conjunto blazer e saia', tipo: 'conjuntos', preco: 399.90, tamanhos: 'P ao G2', imagem: 'https://images.elle.com.br/2025/02/roupas-elegantes-para-o-dia-a-dia-00.jpg', badge: 'elegante' },
  { id: 36, nome: 'Vestido longo drapeado', tipo: 'vestidos', preco: 439.90, tamanhos: 'P ao G3', imagem: 'https://agilita.vtexassets.com/arquivos/ids/761882-800-1200?v=639204446628130000&width=800&height=1200&aspect=true', badge: 'new' },
  { id: 37, nome: 'Vestido midi', tipo: 'vestidos', preco: 369.90, tamanhos: 'P ao G2', imagem: 'https://http2.mlstatic.com/D_NQ_NP_2X_691037-MLB116705879531_082026-T-vestido-longo-babado-fenda-lateral-costas-lastex-elegante.webp', badge: 'novo' },
  { id: 38, nome: 'Conjunto de inverno', tipo: 'conjuntos', preco: 419.90, tamanhos: 'P ao G3', imagem: 'https://cdn.vnda.com.br/amandine/2026/08/17/16_44_25_29_e-mail-20mkt_banner-16086370.jpg?v=1786995869', badge: 'editorial' },
  { id: 39, nome: 'Vestido midi assimétrico', tipo: 'vestidos', preco: 349.90, tamanhos: 'P ao G2', imagem: 'https://static.stealthelook.com.br/wp-content/uploads/2025/11/como-usar-looks-chiques-no-verao-dicas-moda-6-20251104140458.png', badge: 'verão' },
  { id: 40, nome: 'Vestido wrap', tipo: 'vestidos', preco: 389.90, tamanhos: 'PP ao G2', imagem: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQMonSMI-AuNBWYaSZDyaUwxCPPmH8EjBZvcL7Ho8CeBg&s', badge: 'novo' },
  { id: 41, nome: 'Macacão pantalona listrado', tipo: 'conjuntos', preco: 429.90, tamanhos: 'P ao G3', imagem: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTk2emD3jFw2kq3lcUpkD3UQ1U2HJcmJsR22eV8Dym6IFZ5LgHGdgMhqnA&s=10', badge: 'premium' },
  { id: 42, nome: 'Vestido jeans midi', tipo: 'vestidos', preco: 399.90, tamanhos: 'P ao G2', imagem: 'https://image-r.zaxapp.com.br/cdn-cgi/image/w=3840/catalog/product/2486366/6f4041f4-6a41-47e6-8d28-e6d89ec87d9b.webp', badge: 'novo' },
  { id: 43, nome: 'Casaco xadrez', tipo: 'blusas', preco: 309.90, tamanhos: 'P ao G2', imagem: 'https://usofascinius.cdn.magazord.com.br/img/2026/05/produto/33801/03-03425-9.jpg?ims=fit-in/425x635/filters:fill(white)', badge: 'top' },
  { id: 44, nome: 'Conjunto de alfaiataria', tipo: 'conjuntos', preco: 359.90, tamanhos: 'P ao G2', imagem: 'https://claudia.abril.com.br/wp-content/uploads/2026/02/look-casual-chic.jpg?quality=70&strip=info&w=720&crop=1', badge: 'casual' },
  { id: 45, nome: 'Vestido midi com decote', tipo: 'vestidos', preco: 339.90, tamanhos: 'P ao G3', imagem: 'https://m.magazineluiza.com.br/a-static/420x420/vestido-casual-feminino-com-decote-em-v-estampa-irregular-midi-moda-de-verao-elegante-para-ferias-none/aliexpress/203200262/2c70c877309801c9fb7e640a6d63e581.jpeg', badge: 'novo' }
];
let carrinho = [];
let categoriaAtual = 'todos';
const moeda = valor => valor.toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' });
function exibirProdutos() {
  const busca = document.getElementById('search-input').value.toLowerCase().trim();
  const filtrados = produtos.filter(produto => (categoriaAtual === 'todos' || produto.tipo === categoriaAtual) && `${produto.nome} ${produto.tipo} ${produto.tamanhos}`.toLowerCase().includes(busca));
  document.getElementById('product-grid').innerHTML = filtrados.length ? filtrados.map(produto => `<article class="product-card"><div class="product-img-container">${produto.badge ? `<span class="product-badge">${produto.badge}</span>` : ''}<img src="${produto.imagem}" alt="${produto.nome}" loading="lazy"></div><div class="product-info"><h3 class="product-title">${produto.nome}</h3><p class="product-sizes">${produto.tamanhos}</p><div class="product-footer"><span class="product-price">${moeda(produto.preco)}</span><button class="add-to-cart" onclick="adicionarAoCarrinho(${produto.id})">adicionar +</button></div></div></article>`).join('') : '<p class="empty-cart">Nenhuma peça encontrada. Tente outro termo.</p>';
}
function filtrarProdutos(categoria, botao) { categoriaAtual = categoria; document.querySelectorAll('.filter-btn').forEach(item => item.classList.remove('active')); botao.classList.add('active'); exibirProdutos(); }
function toggleCart() { document.getElementById('cart-sidebar').classList.toggle('open'); document.getElementById('cart-overlay').classList.toggle('open'); }
function abrirPesquisa() { document.getElementById('search-panel').classList.add('open'); document.getElementById('search-panel-input').focus(); }
function fecharPesquisa() { document.getElementById('search-panel').classList.remove('open'); }
function executarPesquisa() { document.getElementById('search-input').value = document.getElementById('search-panel-input').value; exibirProdutos(); fecharPesquisa(); document.getElementById('catalogo').scrollIntoView({ behavior: 'smooth' }); }
function adicionarAoCarrinho(id) { const produto = produtos.find(item => item.id === id); carrinho.push(produto); atualizarCarrinho(); document.getElementById('cart-sidebar').classList.add('open'); document.getElementById('cart-overlay').classList.add('open'); }
function removerDoCarrinho(index) { carrinho.splice(index, 1); atualizarCarrinho(); }
function atualizarCarrinho() { const container = document.getElementById('cart-items'); document.getElementById('cart-count').textContent = carrinho.length; document.getElementById('cart-total-price').textContent = moeda(carrinho.reduce((soma, item) => soma + item.preco, 0)); container.innerHTML = carrinho.length ? carrinho.map((item, index) => `<div class="cart-item"><img src="${item.imagem}" alt=""><div><h4>${item.nome}</h4><p>${moeda(item.preco)}</p></div><button class="remove-item" onclick="removerDoCarrinho(${index})" aria-label="Remover ${item.nome}">×</button></div>`).join('') : '<p class="empty-cart">Ainda não tem nada aqui.<br>Uma boa escolha pode mudar o dia.</p>'; }
function finalizarCompra() { if (!carrinho.length) { alert('Sua sacola está vazia.'); return; } alert('Pedido recebido. Obrigado por escolher a Lumière & Style!'); carrinho = []; atualizarCarrinho(); toggleCart(); }
function assinarNewsletter(evento) { evento.preventDefault(); evento.target.innerHTML = '<p style="color: var(--blue); font-size: 13px; padding: 14px 0;">Pronto. Você entrou no movimento.</p>'; document.getElementById('newsletter-message').textContent = 'Confira sua caixa de entrada para confirmar.'; }
document.addEventListener('DOMContentLoaded', () => { document.querySelectorAll('.filter-btn').forEach(botao => botao.addEventListener('click', () => filtrarProdutos(botao.dataset.category, botao))); document.getElementById('search-input').addEventListener('input', exibirProdutos); document.getElementById('search-panel-input').addEventListener('keydown', evento => { if (evento.key === 'Enter') executarPesquisa(); }); document.getElementById('search-panel').addEventListener('click', evento => { if (evento.target.id === 'search-panel') fecharPesquisa(); }); exibirProdutos(); atualizarCarrinho(); });